### ISSUE TITLE
 Close objects that implement io.Closer on delete

### ISSUE THREAD

**Issue by kdima** [patrickmn/go-cache#24]
I think it will be useful if on delete objects that are stored in cache and implement `io.Closer` get closed.

This is especially useful when they get cache evicted. In this case user has no way of closing them manually.

**Comment by pmylund** [comment]
This makes me a little nervous since users might not expect Close() to be called, particularly if it's not a method that works in the "spirit" of io.Closer, or if they've already called it.

I wonder if https://github.com/pmylund/go-cache/issues/21 would satisfy this, or whether an option that's off by default would be best.

**Comment by patrickmn** [comment]
OnEvicted should be fine for now.
