### ISSUE TITLE
Feature Request: access expire time

### ISSUE THREAD

**Issue by Ewan-GrandSlam** [patrickmn/go-cache#34]
It would be nice to be able to access the expire time, e.g. if I have something that needs to be cached now it might not need to be later so the scenario would play out at following:
- Cache an object with an expiry of 10 minutes
- On request for that object, check how much time is left to expire
- If time is within threshold, refresh the data for that key in the background such that we do not refresh during a live request

Let me know what you think

**Comment by alexedwards** [comment]
I came to open a request for the same thing: some form of `GetWithExpiry()` function.

My use case is that I'm using go-cache to store session data for a web application, and want to access the expiry time for writing to a cookie.

Currently it only seems possible to do this through calling `Items()`, which isn't ideal because expiry checks and synchronization would have to be re-implemented outside of go-cache.

I'd be happy to send a pull request implementing something along the lines of:

```go
func (c *cache) GetWithExpiry(k string) (interface{}, time.Time, bool) {
	c.mu.RLock()

	item, found := c.items[k]
	if !found {
		c.mu.RUnlock()
		return nil, time.Time{}, false
	}
	if item.Expiration > 0 {
		if time.Now().UnixNano() > item.Expiration {
			c.mu.RUnlock()
			return nil, time.Time{}, false
		}
	}
	c.mu.RUnlock()
	return item.Object, time.Unix(0, item.Expiration), true
}
```

**Comment by patrickmn** [comment]
Makes sense to me. If you PR this as "GetWithExpiration" (just because that's the terminology everywhere else) with an accompanying test a la the Get() one, and adding yourself to CONTRIBUTORS, I will merge it.

**Comment by patrickmn** [comment]
Merged -- thank you and pardon the delay!
