### ISSUE TITLE
Can I store arbitrary data structure in the cache?

### ISSUE THREAD

**Issue by selforganized** [patrickmn/go-cache#56]
I'd like to cache hyperloglog (something like https://github.com/clarkduvall/hyperloglog) and set expiration times to them. Is that something I can use go-cache for? Thanks.

**Comment by patrickmn** [comment]
You can store anything you want (pointers, structs, ints...) in the cache with some expiration time, yes. For example, that could be a *HyperLogLog.

I don't think it makes sense to attach expiration times to individual hyperloglog values since there's no way to delete from hyperloglog. But if you wanted, you could set OnEvicted() to a function that acts on the eviction of a key, and store struct{}s in the cache.

**Comment by selforganized** [comment]
Thanks. Just want to clarify something. If I put in pointer in the cache, when the cache expires will the object that is pointed to by the pointer purged? Or is it only the pointer itself that is purged while the actual object will still lay around?

**Comment by patrickmn** [comment]
As long as there are no other live references to the object, yes, it will be garbage collected after it's evicted from the cache.
