### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by jonmchan** [patrickmn/go-cache#60]
I'm using go-cache on a gin-gonic web service. When I started to loadtest the system with over 200 threads, the whole application crashed with the following error:

```fatal error: concurrent map read and map write```

When the cache is disabled (always pull from redis), I do not see the errors anymore. Is there possibly a non-thread-safe portion of the code or perhaps something wrong with my code?

```
var cachedJSONTokens *cache.Cache
var cacheInit sync.Once
var cacheTimeout time.Duration

func GetAllowedRoles(name string, skipLocalCache bool) (bool, bool) {
	cacheInit.Do(func () {
		cacheTimeout = // pulled from environment variable
		cachedJSONTokens = cache.New(cacheTimeout, cacheTimeout*10)
	})


	token_query := fmt.Sprintf("token:%s", name)

	var dat string
	var err error
	if x, found := cachedJSONTokens.Get(token_query); !skipLocalCache && found && cacheTimeout > 0 {
		dat = x.(string)
		if dat == "0" {
			return false, false
		}
	} else {
		dat, err = redis.RedisClient().Get(token_query).Result()
		if err != nil {
			if err.Error() == "redis: nil" {
				cachedJSONTokens.Set(token_query,"0",cache.DefaultExpiration)
				return false, false
			} else {
				logger.Error(err)
				return false, false
			}
		}
		cachedJSONTokens.Set(token_query,dat,cache.DefaultExpiration)
	}

	var red_dat model.Token
	if err := json.Unmarshal([]byte(dat), &red_dat); err != nil {
		logger.Panic(err.Error())
	}

	return red_dat.BoolField1, red_dat.BoolField2
} 
```

**Comment by patrickmn** [comment]
I don't see any problem with your code, and I don't see how Set and Get could trigger this:

Set: https://github.com/patrickmn/go-cache/blob/7ac151875ffb48b9f3ccce9ea20f020b0c1596c8/cache.go#L60-L67

Get: https://github.com/patrickmn/go-cache/blob/7ac151875ffb48b9f3ccce9ea20f020b0c1596c8/cache.go#L121-L125

Also, nobody else has reported this problem so far.

It seems far-fetched, but maybe try initializing the cache right away rather than with sync.Once, and see if that helps?

If not, a self-contained reproducing example would be great.

**Comment by jonmchan** [comment]
Thanks for looking at the code. We determined it was another library that was causing the issue. It was just coincidental that disabling the cache alleviated the issue.

**Comment by patrickmn** [comment]
Awesome, glad to hear!
